resource
ListBox
{
name "lstphrases"
rect 70 0 570 460
fgcolor 0.00 0.00 0.00 1.00
bgcolor 1.00 0.50 0.00 1.00
borderstyle 3D_BORDER
additem "Hello Everyone" "append saycvar \"Hello Everyone\""
additem "Hello" "append saycvar \"Hello\""
additem "good bye" "append saycvar \"good bye\""
additem "admin rocks!" "append saycvar \"admin rocks!\""
additem "i smell of wee" "append saycvar \"i smell of wee\""
additem "i am cheating" "append saycvar \"i am cheating\""
additem "i suck" "append saycvar \"i suck\""
additem "i cant stop swearing" "append saycvar \"i cant stop swearing\""
additem "i dont speak english..honest" "append saycvar \"i dont speak english..honest\""
additem "how do you make the gun shoot?" "append saycvar \"how do you make the gun shoot?\""
additem "WHere do i get grenades?" "append saycvar \"WHere do i get grenades?\""
additem "www.mods-r-us.net !!!!!" "append saycvar \"www.mods-r-us.net !!!!!\""
additem "im not gay. my boyfriend is though" "append saycvar \"im not gay. my boyfriend is though\""
additem "nice shot!" "append saycvar \"nice shot!\""
additem "*22" "append saycvar \"*22\""
additem "good game everyone" "append saycvar \"good game everyone\""
additem "i dont know!" "append saycvar \"i dont know!\""
additem "i love this server!" "append saycvar \"i love this server!\""
additem "mhm" "append saycvar \"mhm\""
}
end.
